add_newline = true
palette = "mocha"
command_timeout = 1000

format = """
[](fg:#1e1e2e)\
[ ](bg:#1e1e2e fg:#ffffff)\
[](fg:#1e1e2e bg:#89b4fa)\
$directory\
$git_branch\
$git_status\
[](fg:#89b4fa bg:#1e1e2e)\
$fill\
[](fg:#313244 bg:#1e1e2e)\
[ ⚡ ](bg:#313244 fg:#f9e2af)\
$time\
[](fg:#313244)\
\n$character
"""
# =========================
# Catppuccin Mocha
# =========================
[palettes.mocha]
base = "#1e1e2e"
surface0 = "#313244"
overlay0 = "#6c7086"
text = "#cdd6f4"
blue = "#89b4fa"
green = "#a6e3a1"
peach = "#fab387"
yellow = "#f9e2af"
mauve = "#cba6f7"
red = "#f38ba8"

# =========================
# Directory
# =========================
[directory]
style = "bg:#89b4fa fg:#1e1e2e"
format = "[ $path]($style)"
truncation_length = 3
truncate_to_repo = true

# =========================
# Git
# =========================
[git_branch]
symbol = "  "
style = "bg:blue fg:base"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:blue fg:base"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "●"
staged = "+"
renamed = "»"
deleted = "✘"
format = "[$all_status$ahead_behind]($style)"

# =========================
# NodeJS
# =========================
[nodejs]
symbol = " ⬢ "
style = "bg:blue fg:red"
format = "[ $symbol$version ]($style)"

# =========================
# PHP / Laravel
# =========================
[php]
symbol = "  "
style = "bg:blue fg:mauve"
format = "[ $symbol$version ]($style)"

# =========================
# Python
# =========================
[python]
symbol = " 🐍 "
style = "bg:blue fg:yellow"
format = "[ $symbol$version ]($style)"

# =========================
# Docker
# =========================
[docker_context]
symbol = " 🐳 "
style = "bg:blue fg:peach"
format = "[ $symbol$context ]($style)"

# =========================
# Fill
# =========================
[fill]
symbol = "·"
style = "fg:overlay0 bg:base"

# =========================
# Time
# =========================
[time]
disabled = false
time_format = "%I:%M:%S %p"
style = "bg:surface0 fg:text"
format = "[ at $time ]($style)"

# =========================
# Prompt
# =========================
[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
