format = """\
[╭╴](fg:arrow)\
     $username\
     $os\
     $git_branch\
     $git_status\
(\
    at \
    $directory\
)\
    $fill $cmd_duration $time\
(\
    $python\
    $nodejs\
    $rust\
    $php\
)
[╰─](fg:arrow)$character\
"""
# Add the modules you need

# Disable the blank line at the start of the prompt
add_newline = true

palette = "normal"

[palettes.normal]
arrow = "#B3BCFD"
os = "#B3BCFD"
os_admin = "#B3BCFD"
directory = "#B3BCFD"
time = "#B3BCFD"
node = "#a5e6ba"
php = "#B0B3D6"
git = "#f17f29"
git_status = "#DFEBED"
python = "#FFD43B"
java = "#F86279"
rust = "#ffdac6"
laravel = "#F05340"
duration = "#ce4257"
text_color = "#EDF2F4"
text_light = "#26272A"

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[  $user](fg:$style) '
disabled = false
show_always = true

[character]
success_symbol = "[>](fg:arrow)"
error_symbol = "[>](fg:red)"

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[time]
disabled = false
format = "[󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
disabled = false
format = "took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold fg:git"
symbol = "  "
disabled = false

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = "bold fg:git_status"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "●"
staged = "+"
renamed = "»"
deleted = "✘"
disabled = true

[nodejs]
format = "[ $symbol$version ]($style)"
style = "fg:node"
symbol = " "
disabled = false

[python]
format = '[ ${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
style = "fg:python"
symbol = " "
disabled = false

[php]
format = "[ $symbol$version ]($style)"
style = "fg:laravel"
symbol = " "
disabled = false

[rust]
format ="[ $symbol$version ]($style)"
style = "fg:rust"
symbol = " "
disabled = false
